import Head from 'next/head';
import styles from '@/styles/Home.module.css'
export default function Home() {
  return (
    <>
      <Head>
        <title>Mvp1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>MVP1 Project Has been Setup 🔥</h1>

      </main>
    </>
  )
}
