import React, { useState } from "react";
import Layout from "@/components/setting_profile/Layout";
import Head from "next/head";
import { LinkProps } from "@/components/setting_profile/SidebarLinks";
import empty_wallet from "@/public/assets/setting-profile/icons/setting/empty-wallet.svg";
import empty_wallet_hover from "@/public/assets/setting-profile/icons/setting/empty-wallet-hover.svg";
import manage_email from "@/public/assets/setting-profile/icons/setting/manage-email.svg";
import manage_email_hover from "@/public/assets/setting-profile/icons/setting/manage-email-hover.svg";
import verification from "@/public/assets/setting-profile/icons/setting/shield-tick.svg";
import verification_hover from "@/public/assets/setting-profile/icons/setting/shield-tick-hover.svg";
import bubble from "@/public/assets/setting-profile/icons/setting/bubble.svg";
import bubble_hover from "@/public/assets/setting-profile/icons/setting/bubble-hover.svg";
import notification from "@/public/assets/setting-profile/icons/setting/notification.svg";
import notification_hover from "@/public/assets/setting-profile/icons/setting/notification-hover.svg";
import ManageWallet from "@/components/setting_profile/setting/ManageWallet";
const Setting = () => {
	const [openModal, setOpenModal] = useState<boolean>(false);
	const handleOpen = () => {
		window.location.hash === "";
		setOpenModal(true);
	};
	const handleClose = () => setOpenModal(false);
	const SidebarLinksData: LinkProps[] = [
		{
			icon: [empty_wallet, empty_wallet_hover],
			title: "Manage Wallet",
			link: "#/setting/manage-wallet",
			component: <ManageWallet/>,
			isFirstLinkToLoad: true,
			isFirstComponentToLoad: true,
		},
		{
			icon: [manage_email, manage_email_hover],
			title: "Manage Email",
			link: "#/setting/manage-email",
			component: <div>Manage Email</div>,
		},
		
		{
			icon: [verification, verification_hover],
			title: "Verification",
			link: "#/setting/verification",
			component: <div>Verification</div>,
		},
		{
			icon: [bubble, bubble_hover],
			title: "Preferences",
			link: "#/setting/preferences",
			component: <div>Preferences</div>,
		},
		{
			icon: [notification, notification_hover],
			title: "Notifications",
			link: "#/setting/notifications",
			component: <div>Notifications</div>,
		},
	];
	return (
		<>
			<Head>
				<title>Settings</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<button
					onClick={handleOpen}
					style={{ border: "1px solid black" }}
				>
					{" "}
					Open Modal
				</button>
				<Layout
					headerTitles="Settings"
					openModal={openModal}
					handleClose={handleClose}
					sidebarLinksData={SidebarLinksData}
				/>
			</main>
		</>
	);
};
export default Setting;
