import React, { useState, FormEvent, ChangeEvent } from "react";
import styles from "@/styles/basic-info/basic-info.module.css";
import Head from "next/head";
import LogoWithDescriptiveLabel from "@/components/LogoWithDescriptiveLabel";
import * as Yup from "yup";
import { useRouter } from "next/router";
import seaclub_logo from "@/public/assets/basic-info/logo/seaclub_logo.svg";
import CustomizedLoginButton from "@/components/CustomizedLoginButton";
import GobackButton from "@/components/GobackButton";

const BasicInfo = () => {
	const router = useRouter();
	const [linkedinURL, setLinkedinURL] = useState<string>("");
	const [linkedinURLError, setlinkedinURLError] = useState<string>("");

	const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
		event.preventDefault();
		const basicInfoSchema = Yup.object().shape({
			linkedinURL: Yup.string()
				.url()
				.matches(/^(http(s)?:\/\/)?([\w]+\.)?linkedin\.com\/(pub|in|profile)\/([-a-zA-Z0-9]+)\/*/gm
					, 'Please enter a valid linkedin url')
				.required("Please enter your linkedin url"),
		});

		const validateForm = await basicInfoSchema
			.validate({ linkedinURL }, { abortEarly: false })
			.catch((error) => error);

		if (validateForm.errors) {
			if (validateForm.errors.length > 0) {
				console.log(validateForm.errors);
				setlinkedinURLError(validateForm.errors[0]);
			}
		} else {
			setLinkedinURL("");
			setlinkedinURLError("");
		}
	};
	return (
		<>
			<Head>
				<title>Basic Infos</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<form className={styles.basic_info} onSubmit={handleSubmit}>
				<GobackButton />
				<div className={styles.basic_info_form}>
					<LogoWithDescriptiveLabel
						description="Get Started"
						src={seaclub_logo}
					/>
					<div className={styles.basic_info_inputs}>
						<span className={styles.enter_basic_info}>
							Enter Your Basic Info{" "}
						</span>
						<button
							className={styles.enter_basic_info_manually}
							onClick={() => router.push("/basic-info/input")}
							type="button"
						>
							Enter basic info manually
						</button>
						<span className={styles.or_separator}>Or</span>
						<div className={styles.linkedin_section}>
							<input
								type="text"
								name="linkedin url"
								placeholder="Provide LinkedIn company page URL for basic info."
								onChange={(
									event: ChangeEvent<HTMLInputElement>
								) => setLinkedinURL(event.target.value)}
								value={linkedinURL}
							/>
							{linkedinURLError && (
								<span className={styles.bad_linkedin_url}>
									{linkedinURLError}{" "}
								</span>
							)}
						</div>
					</div>
					<div className={styles.continue}>
						<CustomizedLoginButton title="Continue" width="16.06" height="3.12" fontSize="1.2" />
					</div>
				</div>
			</form>
		</>
	);
};
export default BasicInfo;
