/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useSelector } from "react-redux";
import { PasswordRecoverySelector } from "@/state_management/features/PasswordRecoverySlice";
import Head from "next/head";
import GobackButton from "@/components/GobackButton";
import LogoWithDescriptiveLabel from "@/components/LogoWithDescriptiveLabel";
import Link from "next/link";
import seaclub_logo from "@/public/assets/login/logo/seaclub_logo.svg";
const PasswordRecoveryWithEmail = () => {
	const email = useSelector(PasswordRecoverySelector)
	return (
		<>
			<Head>
				<title>Password Recovery</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen flex  justify-center ">
				<GobackButton />
				<div className="flex flex-col items-center h-[50em] w-[52.12em]  mt-[2.87em] ">
					<LogoWithDescriptiveLabel description="Reset your password" src={seaclub_logo} />
					<div className="flex flex-col mt-[2.81em] w-[41.87em] h-[12.18em] font-helvetica-medium text-[1.3em] text-center f ">
						<p className="text-cimen">We sent a reset password email to <span>{email}</span> please <br /> click the reset password link to set your new password. </p>
						<p className="text-cimen mt-4">Haven't you receive the email yet? <br /> Please check your spam folder, or <Link href='' className="text-keinBlue">Resend instructions</Link> </p>
					</div>
				</div>
			</main>
		</>
	);
};
export default PasswordRecoveryWithEmail;
