import React, { useState } from "react";
import styles from "../../styles/login/login.module.css";
import Head from "next/head";
import Link from "next/link";
import GobackButton from "@/components/GobackButton";
import LogoWithDescriptiveLabel from "@/components/LogoWithDescriptiveLabel";
import SocialMediaContainer from "@/components/SocialMediaContainer";
import seaclub_logo from "@/public/assets/login/logo/seaclub_logo.svg";
import { useRouter } from "next/router";
import WalletConnection from "@/components/WalletConnection";
const Login = () => {
	const router = useRouter();
	const [open, setOpen] = useState<boolean>(false)
	return (
		<>
			<Head>
				<title>Login</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.login}>
				<GobackButton />
				<div className={styles.login_form}>
					<LogoWithDescriptiveLabel description="Welcome Back" src={seaclub_logo} />
					<div className={styles.login_inputs}>
						<span className={styles.connect_with_us_span}>
							Connect with{" "}
						</span>
						<button className={styles.continue_with_email_button} onClick={() => router.push('/login/email')}>
							Continue with Email
						</button>
						<span className={styles.or_separator}>Or</span>
						<button onClick={() => setOpen(true)} className={styles.continue_with_wallet_button}>
							Continue with Wallet
						</button>
						<Link href="/sign-up" className={styles.go_to_registerPage}>
							<span>Dont have an account yet?</span>
							<span onClick={() => router.push('/sign-up')} className={styles.register_now_link}>
								Register Now
							</span>
						</Link>
					</div>
					<div className={styles.log_into_social_media}>
						<span className={styles.or_connect_with_separator}>
							Or Connect with
						</span>
						<div className={styles.social_media_container}>
							<SocialMediaContainer />
						</div>
					</div>
					<WalletConnection open={open} setOpen={setOpen} />
				</div>
			</main>
		</>
	);
};
export default Login;
