/* eslint-disable react/no-unescaped-entities */
import React from "react";
import Head from "next/head";
import GobackButton from "@/components/GobackButton";
import { useRouter } from "next/router";
import LogoWithDescriptiveLabel from "@/components/LogoWithDescriptiveLabel";
import successLogo from "@/public/assets/login/icons/check.svg"
const SuccessPasswordRecovery = () => {
	const router = useRouter();
	const goBackToLoginPage = () => {
		router.push("/login");
	};
	return (
		<>
			<Head>
				<title>Password recovered</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen flex items-center justify-center ">
				<GobackButton />
				<div className="flex flex-col items-center h-[50em] w-[52.12em]  mt-[13.75em] ">
					<div className="flex flex-col items-center w-[26.25em] h-[11.31em] ">
						<LogoWithDescriptiveLabel description="Your password was updated" src={successLogo} />
					</div>
					<button
						type="submit"
						onClick={goBackToLoginPage}
						className="flex items-center justify-center mt-[2.81em] bg-black p-[.625em] 
                            w-[16.06em] h-[3.125em] text-white border rounded-[6.25em] font-helvetica-regular font-light shadow-boxShadowBlack
                             hover:opacity-[.8]"
					>
						Log In
					</button>
				</div>
			</main>
		</>
	);
};
export default SuccessPasswordRecovery;
