apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: seaclub/swagger-ui:latest
          env:
            - name: PORT
              value: '5010'
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui-srv
spec:
  selector:
    app: swagger-ui
  ports:
    - name: swagger-ui
      protocol: TCP
      port: 5010
      targetPort: 5010