import React from "react";
import { useRouter } from "next/router";
import FirstPortfolioTemplate from "@/components/profile/add_section/portfolio/edit-portfolio-template/FirstPortfolioTemplate/FirstPortfolioTemplate";

import Head from "next/head";
import SecondPortfolioTemplate from "@/components/profile/add_section/portfolio/edit-portfolio-template/SecondPortfolioTemplate/SecondPortfolioTemplate";
import ThirdPortfolioTemplate from "@/components/profile/add_section/portfolio/edit-portfolio-template/ThirdPortfolioTemplate/ThirdPortfolioTemplate";
const Edit = () => {
	const router = useRouter();
	const portfolioId = router.query.id;
	return (
		<div>
			<Head>
				<title>Edit portfolio template </title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{portfolioId === "1" && <FirstPortfolioTemplate />}
				{portfolioId === "2" && <SecondPortfolioTemplate />}
				{portfolioId === "3" && <ThirdPortfolioTemplate />}
			</main>
		</div>
	);
};
export default Edit;
